### ISSUE TITLE
BUGGY WEBSITE

### ISSUE THREAD

**Issue by PitamahBhishma-0** [Abiral07/Code-Blogger#1]
WHY IS EVERY THING BUGS HERE??
PLEASE FIX ITTTTTTTTTTTTTTTTTTTTTT...................................................

**Comment by Abiral07** [comment]
NONE SENSE

**Comment by PitamahBhishma-0** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
